import fs from 'fs';
import { createHash } from 'crypto';
import path from 'path';
import type { Reporter, TestCase, TestResult } from '@playwright/test/reporter';

/**
 * Safety net for CHARTER.md's rule #5 ("produce a precise bug report") —
 * catches any FAIL where the test itself didn't call attachBugReport()
 * (helpers/bugReport.ts). Writes a deliberately unfinished skeleton to
 * bug-reports/auto/ with everything that CAN be captured automatically
 * (title, error, stack, attachments) and leaves classification/root cause
 * as "Needs Investigation" — this reporter does not diagnose, only records.
 * A hand-authored report for the same failure always supersedes this one.
 */
export default class BugReportReporter implements Reporter {
  private reportsDir = path.resolve(__dirname, '..', 'bug-reports', 'auto');

  onTestEnd(test: TestCase, result: TestResult): void {
    if (result.status !== 'failed' && result.status !== 'timedOut') return;

    const hasManualReport = result.attachments.some((a) => a.name === 'bug-report');
    if (hasManualReport) return;

    fs.mkdirSync(this.reportsDir, { recursive: true });

    // Stable filename per test — a re-run refreshes the skeleton in place
    // rather than accumulating one file per run.
    //
    // Built from the END of the title path plus a hash of the full path.
    // Truncating the START collided: every test in one describe block
    // shares a long common prefix, so three distinct failures all produced
    // the same 80-char slug and silently overwrote each other, leaving one
    // file for three bugs. The distinguishing text is always the tail.
    const fullTitle = test.titlePath().join(' > ');
    const hash = createHash('sha1').update(fullTitle).digest('hex').slice(0, 8);
    const tail = test
      .titlePath()
      .slice(-2)
      .join('-')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '')
      .slice(0, 70);
    const filePath = path.join(this.reportsDir, `${tail}-${hash}.md`);

    const errorMessage =
      result.errors.map((e) => e.message ?? String(e)).join('\n---\n') || '(no error message captured)';
    const evidence = result.attachments.length
      ? result.attachments.map((a) => `- ${a.name}${a.path ? `: ${a.path}` : ''}`).join('\n')
      : '- (no attachments captured for this run)';

    const content = `# ${test.title}

- **Priority**: Unknown — needs triage
- **Classification**: UNCLASSIFIED — needs investigation (Application bug / QA bug / Environment issue / Expected behavior)
- **Status**: Needs Investigation
- **Project**: ${test.parent.project()?.name ?? 'unknown'}
- **Test case**: ${test.titlePath().slice(1).join(' > ')}
- **Result**: ${result.status} (${result.retry > 0 ? `retry #${result.retry}` : 'first attempt'}, ${Math.round(result.duration)}ms)

## Error
\`\`\`
${errorMessage}
\`\`\`

## Evidence
${evidence}

---
Auto-generated by reporters/bugReportReporter.ts because this test failed
without a manually-classified report attached via helpers/bugReport.ts's
attachBugReport(). Per CHARTER.md, this reporter records failures — it does
not diagnose or fix them. Replace this file with a properly classified
report (see CHARTER.md's bug report template) once investigated, or confirm
it as a QA/test bug and delete it.
`;
    fs.writeFileSync(filePath, content);
  }
}
